--#SET TERMINATOR ;
SET CURRENT SCHEMA LOGGER_1A;

-- Drops all objects.
DROP MODULE LOGGER;

DROP VIEW LOG_MESSAGES;

DROP TRIGGER T14_LOGS_UNIQUE_DATE;

DROP TRIGGER T13_CONF_APPENDERS_PATTERN;

DROP TRIGGER T12_APPENDERS_GREATER_EQUAL_ZERO;

DROP TRIGGER T11_EFFECTIVE_DELETE_CACHE;

DROP TRIGGER T10_INSERT_CACHE;

DROP TRIGGER T9_EFFECTIVE_ROOT_LOGGER_UNDELETABLE;

DROP TRIGGER T8_EFFECTIVE_LEVEL_UPDATE;

DROP TRIGGER T7_EFFECTIVE_LEVEL_UPDATE_DELETE;

DROP TRIGGER T6_EFFECTIVE_NO_UPDATE;

DROP TRIGGER T5_EFFECTIVE_INSERT;

DROP TRIGGER T4_EFFECTIVE_CHECK;

DROP TRIGGER T3_CONF_LOGGER_SYNC;

DROP TRIGGER T2_CONF_LOGGERS_NO_UPDATE;

DROP TRIGGER T1_CONF_LOGGERS_ID;

DROP PUBLIC ALIAS LOGGER FOR MODULE;

DROP PUBLIC ALIAS LOGADMIN FOR MODULE;

DROP SCHEMA LOGGER_1A RESTRICT;