--#SET TERMINATOR ;
SET CURRENT SCHEMA LOGGER;

-- Drops all objects.
DROP MODULE LOGGER;

DROP TRIGGER CHECK_CONF_LOGGER;

DROP TRIGGER CHECK_CONF_LOGGER_EFFECTIVE;

DROP TRIGGER ROOT_LOGGER_UNDELETABLE;

DROP TRIGGER REF_ID_GREATER_EQUAL_ZERO;

DROP TRIGGER APPENDER_GREATER_EQUAL_ZERO;

DROP TABLE LOGS;

DROP TABLE REFERENCES;

DROP TABLE CONF_APPENDERS;

DROP TABLE APPENDERS;

DROP TABLE CONF_LOGGERS_EFFECTIVE;

DROP TABLE CONF_LOGGERS;

DROP TABLE LEVELS;

DROP TABLE CONFIGURATION;

DROP SCHEMA LOGGER RESTRICT;

DROP TABLESPACE LOGGER_SPACE;