--#SET TERMINATOR ;
SET CURRENT SCHEMA LOGGER_1A;

-- Drops all objects.
DROP VIEW LOG_MESSAGES;

DROP PUBLIC ALIAS LOGGER FOR MODULE;

DROP PUBLIC ALIAS LOGADMIN FOR MODULE;

DROP MODULE LOGGER;

DROP MODULE LOGADMIN;

DROP SCHEMA LOGGER_1A RESTRICT;