--#SET TERMINATOR ;
SET CURRENT SCHEMA LOGGER_1A;

DROP TRIGGER T1_LOGS_UNIQUE_DATE;

DROP TRIGGER T1_CONF_APPENDERS_PATTERN;

DROP TRIGGER T1_APPENDERS_GREATER_EQUAL_ZERO;

DROP TRIGGER T9_EFFECTIVE_DELETE_CACHE;

DROP TRIGGER T8_INSERT_CACHE;

DROP TRIGGER T7_EFFECTIVE_ROOT_LOGGER_UNDELETABLE;

DROP TRIGGER T6_EFFECTIVE_LEVEL_UPDATE;

DROP TRIGGER T5_EFFECTIVE_LEVEL_UPDATE_DELETE;

DROP TRIGGER T4_EFFECTIVE_NO_UPDATE;

DROP TRIGGER T3_EFFECTIVE_INSERT;

DROP TRIGGER T2_EFFECTIVE_NO_DUPLICATES;

DROP TRIGGER T1_EFFECTIVE_CHECK;

DROP TRIGGER T4_CONF_LOGGER_SYNC_DELETE;

DROP TRIGGER T3_CONF_LOGGER_SYNC;

DROP TRIGGER T2_CONF_LOGGERS_NO_UPDATE;

DROP TRIGGER T1_CONF_LOGGERS_ID;

DROP TRIGGER T3_LEVELS_DELETE;

DROP TRIGGER T2_LEVELS_NO_UPD;

DROP TRIGGER T1_LEVELS_CONS;

DROP TRIGGER T1_CONF_CACHE;