--#SET TERMINATOR ;
SET CURRENT SCHEMA LOGGER_1A;

-- Drops all objects.
DROP MODULE LOGGER;

DROP MODULE LOGADMIN;

DROP VIEW LOG_MESSAGES;

DROP TRIGGER T1_LOGS_UNIQUE_DATE;

DROP TRIGGER T1_CONF_APPENDERS_PATTERN;

DROP TRIGGER T1_APPENDERS_GREATER_EQUAL_ZERO;

DROP TRIGGER T8_EFFECTIVE_DELETE_CACHE;

DROP TRIGGER T7_INSERT_CACHE;

DROP TRIGGER T6_EFFECTIVE_ROOT_LOGGER_UNDELETABLE;

DROP TRIGGER T5_EFFECTIVE_LEVEL_UPDATE;

DROP TRIGGER T4_EFFECTIVE_LEVEL_UPDATE_DELETE;

DROP TRIGGER T3_EFFECTIVE_NO_UPDATE;

DROP TRIGGER T2_EFFECTIVE_INSERT;

DROP TRIGGER T1_EFFECTIVE_CHECK;

DROP TRIGGER T3_CONF_LOGGER_SYNC;

DROP TRIGGER T2_CONF_LOGGERS_NO_UPDATE;

DROP TRIGGER T1_CONF_LOGGERS_ID;

DROP TRIGGER T2_LEVELS_NO_UPD;

DROP TRIGGER T1_LEVELS_CONS;

DROP PUBLIC ALIAS LOGGER FOR MODULE;

DROP PUBLIC ALIAS LOGADMIN FOR MODULE;

DROP SCHEMA LOGGER_1A RESTRICT;