--#SET TERMINATOR ;
SET CURRENT SCHEMA LOGGER_1A;

/**
 * TODO DESCRIPTION
 *
 * Made in COLOMBIA.
 */

-- Schema for logger utility's objects.
CREATE SCHEMA LOGGER_1A;

COMMENT ON SCHEMA LOGGER_1A IS 'Schema for objects of the log4db2 utility';

-- Module for all code for the logger utility.
CREATE OR REPLACE MODULE LOGGER;

CREATE PUBLIC ALIAS LOGGER FOR MODULE LOGGER;

-- Module version.
ALTER MODULE LOGGER PUBLISH
  VARIABLE VERSION VARCHAR(32) CONSTANT '2012-10-08 1-Alpha';

-- Procedure that show the configuration.
ALTER MODULE LOGGER PUBLISH
  PROCEDURE SHOW_CONF (
  );

-- Public functions and procedures.
-- Procedure to retrieve the complete logger name.
ALTER MODULE LOGGER PUBLISH
  FUNCTION GET_LOGGER_NAME (
  IN LOG_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID
  ) RETURNS VARCHAR(256);

-- Procedure to write logs.
ALTER MODULE LOGGER PUBLISH
  PROCEDURE LOG (
  IN LOGGER_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID,
  IN LEVEL_ID ANCHOR LOGDATA.LEVELS.LEVEL_ID,
  IN MESSAGE ANCHOR LOGDATA.LOGS.MESSAGE
  );

-- Procedure to write logs in debug mode.
ALTER MODULE LOGGER PUBLISH
  PROCEDURE DEBUG (
  IN LOGGER_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID,
  IN MESSAGE ANCHOR LOGDATA.LOGS.MESSAGE
  );

-- Procedure to write logs in info mode.
ALTER MODULE LOGGER PUBLISH
  PROCEDURE INFO (
  IN LOGGER_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID,
  IN MESSAGE ANCHOR LOGDATA.LOGS.MESSAGE
  );

-- Procedure to write logs in warn mode.
ALTER MODULE LOGGER PUBLISH
  PROCEDURE WARN (
  IN LOGGER_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID,
  IN MESSAGE ANCHOR LOGDATA.LOGS.MESSAGE
  );

-- Procedure to write logs in error mode.
ALTER MODULE LOGGER PUBLISH
  PROCEDURE ERROR (
  IN LOGGER_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID,
  IN MESSAGE ANCHOR LOGDATA.LOGS.MESSAGE
  );

-- Procedure to write logs in fatal mode.
ALTER MODULE LOGGER PUBLISH
  PROCEDURE FATAL (
  IN LOGGER_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID,
  IN MESSAGE ANCHOR LOGDATA.LOGS.MESSAGE
  );

-- Procedure to register the logger.
ALTER MODULE LOGGER PUBLISH
  PROCEDURE GET_LOGGER (
  IN NAME VARCHAR(256),
  OUT LOGGER_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID
  );

-- Procedure that shows the used loggers.
ALTER MODULE LOGGER PUBLISH
  PROCEDURE SHOW_LOGGERS (
  );

-- Procedure that shows the logs.
ALTER MODULE LOGGER PUBLISH
  PROCEDURE LOGS (
  IN LENGTH SMALLINT DEFAULT 72,
  IN QTY SMALLINT DEFAULT 100
  );

-- View modified to retrieve the logger name.
CREATE OR REPLACE VIEW LOG_MESSAGES 
  (DATE, LEVEL, LOGGER, MESSAGE) AS
  SELECT TIMESTAMP(L.DATE) AS DATE, LE.NAME AS LEVEL,
  LOGGER.GET_LOGGER_NAME(L.LOGGER_ID) AS LOGGER, L.MESSAGE
  FROM LOGDATA.LOGS AS L LEFT JOIN LOGDATA.LEVELS AS LE
  ON L.LEVEL_ID = LE.LEVEL_ID;