--#SET TERMINATOR @

/**
 * Tests different names for loggers.
 */

SET CURRENT SCHEMA LOGGER_1A @

BEGIN
-- Reserved names for errors.
DECLARE SQLCODE INTEGER DEFAULT 0;
DECLARE SQLSTATE CHAR(5) DEFAULT '0000';

DECLARE STRING VARCHAR(32);
DECLARE EXPECTED_ID ANCHOR DATA TYPE TO LOGDATA.CONF_LOGGERS.LOGGER_ID;
DECLARE ACTUAL_ID ANCHOR DATA TYPE TO LOGDATA.CONF_LOGGERS.LOGGER_ID;
DECLARE LAST_VALUE ANCHOR DATA TYPE TO LOGDATA.CONF_LOGGERS.LOGGER_ID;

-- For any other SQL State.
DECLARE CONTINUE HANDLER FOR SQLWARNING
  INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Warning SQLCode ' || SQLCODE || '-SQLState ' || SQLSTATE);
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
  INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Exception SQLCode ' || SQLCODE || '-SQLState ' || SQLSTATE);
DECLARE CONTINUE HANDLER FOR NOT FOUND
  INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Not found SQLCode ' || SQLCODE || '-SQLState ' || SQLSTATE);

-- Prepares the environment.
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('TestGetLogger: Preparing environment');

SELECT LOGGER_ID INTO LAST_VALUE FROM FINAL TABLE (
  INSERT INTO LOGDATA.CONF_LOGGERS_EFFECTIVE (NAME, PARENT_ID, LEVEL_ID)
  VALUES ('TEST', 0, 0));
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE
  WHERE LOGGER_ID <> 0;

-- Tests empty string.
SET STRING = '';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test01: >' || STRING || '<');
SET EXPECTED_ID = 0;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests a whitespace.
SET STRING = ' ';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test02: >' || STRING || '<');
SET EXPECTED_ID = 0;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests a dot.
SET STRING = '.';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test03: >' || STRING || '<');
SET EXPECTED_ID = 0;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests two dots.
SET STRING = '..';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test04: >' || STRING || '<');
SET EXPECTED_ID = 0;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests a letter.
SET STRING = 'a';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test05: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 1;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests a letter followed by a dot.
SET STRING = 'b.';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test06: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 2;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests two valid levels.
SET STRING = 'c.c';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test07: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 4;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests a dot preceded by a dot.
SET STRING = '.d';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test08: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 5;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests a letter surrrounded by dots.
SET STRING = '.e.';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test09: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 6;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests three valid levels.
SET STRING = 'f.g.h';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test10: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 9;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests three valid levels (multiple letters).
SET STRING = 'ii.jj.kk';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test11: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 12;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests a multi letter level.
SET STRING = 'lll';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test12: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 13;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests two multi letters levels.
SET STRING = 'mm.nn';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test13: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 15;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests three multi letters levels.
SET STRING = '111.222.333';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test14: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 18;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Tests a letter surrrounded by spaces.
SET STRING = ' p ';
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Test15: >' || STRING || '<');
SET EXPECTED_ID = LAST_VALUE + 19;
CALL LOGGER.GET_LOGGER(STRING, ACTUAL_ID);
IF (EXPECTED_ID <> ACTUAL_ID) THEN
 INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('Error in test ' || STRING || ' expected ' || EXPECTED_ID || ' ACTUAL ' || COALESCE(ACTUAL_ID,-1));
END IF;

-- Cleans the environment.
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE
  WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.LOGS (MESSAGE) VALUES ('TestGetLogger: Finished succesfully');

END @