--#SET TERMINATOR ;

/*
Copyright (c) 2012 - 2014, Andres Gomez Casanova (AngocA)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

SET CURRENT SCHEMA LOGGER_1A;

DROP TRIGGER T1_LOGS_UNIQUE_DATE;

DROP TRIGGER T1_CONF_APPENDERS_PATTERN;

DROP TRIGGER T1_APPENDERS_GREATER_EQUAL_ZERO;

DROP TRIGGER T8_EFFECTIVE_DELETE_CACHE;

DROP TRIGGER T7_EFFECTIVE_ROOT_LOGGER_UNDELETABLE;

DROP TRIGGER T6_EFFECTIVE_LEVEL_UPDATE;

DROP TRIGGER T5_EFFECTIVE_LEVEL_UPDATE_DELETE;

DROP TRIGGER T4_EFFECTIVE_NO_UPDATE;

DROP TRIGGER T3_EFFECTIVE_INSERT;

DROP TRIGGER T2_EFFECTIVE_NO_DUPLICATES;

DROP TRIGGER T1_EFFECTIVE_CHECK;

DROP TRIGGER T4_CONF_LOGGER_SYNC_DELETE;

DROP TRIGGER T3_CONF_LOGGER_SYNC;

DROP TRIGGER T2_CONF_LOGGERS_NO_UPDATE;

DROP TRIGGER T1_CONF_LOGGERS_ID;

DROP TRIGGER T3_LEVELS_DELETE;

DROP TRIGGER T2_LEVELS_NO_UPD;

DROP TRIGGER T1_LEVELS_CONS;

DROP TRIGGER T1_CONF_CACHE;