--#SET TERMINATOR ;

/*
Copyright (c) 2012 - 2014, Andres Gomez Casanova (AngocA)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

SET CURRENT SCHEMA LOGGER_1B;

/**
 * Drops the trigger in the opposite order as they were created.
 *
 * Version: 2014-02-14 1-Alpha
 * Author: Andres Gomez Casanova (AngocA)
 * Made in COLOMBIA.
 */

DROP TRIGGER T1_LGS_UNI_DATE;

DROP TRIGGER T1_CNF_APP_PATT;

DROP TRIGGER T1_APP_GE_0;

DROP TRIGGER T4_EFF_ROOT_UNDEL;

DROP TRIGGER T3_EFF_LVL_UPD;

DROP TRIGGER T2_EFF_NO_UPD;

DROP TRIGGER T1_EFF_LVL_ID;

DROP TRIGGER T4_CNFLGER_CLN;

DROP TRIGGER T3_CNFLGR_SYN;

DROP TRIGGER T2_CNFLGR_NO_UPD;

DROP TRIGGER T1_CNFLGR_ID;

DROP TRIGGER T3_LVL_DEL;

DROP TRIGGER T2_LVL_NO_UPD;

DROP TRIGGER T1_LVL_CON;

DROP TRIGGER T1_CNF_CCHE;

