--#SET TERMINATOR @

/*
Copyright (c) 2012 - 2014, Andres Gomez Casanova (AngocA)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/**
 * Tests the layout of the conf_appenders table.
 */

SET CURRENT SCHEMA LOGGER_1A @

BEGIN
-- Reserved names for errors.
DECLARE SQLCODE INTEGER DEFAULT 0;
DECLARE SQLSTATE CHAR(5) DEFAULT '00000';

DECLARE APPENDER_NAME ANCHOR LOGDATA.CONF_LOGGERS.NAME;
DECLARE APPENDER_ID ANCHOR LOGDATA.CONF_APPENDERS.REF_ID;
DECLARE EXPECTED_MSG ANCHOR LOGDATA.LOGS.MESSAGE;
DECLARE ACTUAL_MSG ANCHOR LOGDATA.LOGS.MESSAGE;
DECLARE LOGGER_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID;
DECLARE LOGGER_NAME ANCHOR LOGDATA.CONF_LOGGERS.NAME;

-- Prepares the environment.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (4, 'TestsReferences: Preparing environment');
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS;
COMMIT;

-- Test1: Check the id.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test1: Check the id');
DELETE FROM LOGDATA.CONF_LOGGERS;
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_LOGGERS (LOGGER_ID, NAME, PARENT_ID, LEVEL_ID)
  VALUES (0, 'ROOT', NULL, 5);
SET LOGGER_NAME = 'Test1';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
INSERT INTO LOGDATA.CONF_LOGGERS (LOGGER_ID, NAME, PARENT_ID, LEVEL_ID)
  VALUES (LOGGER_ID, LOGGER_NAME, 0, 5);
SET APPENDER_NAME='Test1';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%I');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.FATAL(LOGGER_ID, 'Message test');
SET EXPECTED_MSG=SYSPROC.MON_GET_APPLICATION_ID();
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS;
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test2: Check the application name.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test2: Check the application name');
DELETE FROM LOGDATA.CONF_LOGGERS;
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_LOGGERS (LOGGER_ID, NAME, PARENT_ID, LEVEL_ID)
  VALUES (0, 'ROOT', NULL, 5);
SET LOGGER_NAME = 'Test2';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
INSERT INTO LOGDATA.CONF_LOGGERS (LOGGER_ID, NAME, PARENT_ID, LEVEL_ID)
  VALUES (LOGGER_ID, LOGGER_NAME, 0, 5);
SET APPENDER_NAME='Test2';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%N');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.FATAL(LOGGER_ID, 'Message test');
SELECT APPLICATION_NAME INTO EXPECTED_MSG
  FROM TABLE(MON_GET_CONNECTION(SYSPROC.MON_GET_APPLICATION_HANDLE(),-1));
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS;
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test3: Check the handle.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test3: Check the handle');
DELETE FROM LOGDATA.CONF_LOGGERS;
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_LOGGERS (LOGGER_ID, NAME, PARENT_ID, LEVEL_ID)
  VALUES (0, 'ROOT', NULL, 5);
SET LOGGER_NAME = 'Test3';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
INSERT INTO LOGDATA.CONF_LOGGERS (LOGGER_ID, NAME, PARENT_ID, LEVEL_ID)
  VALUES (LOGGER_ID, LOGGER_NAME, 0, 5);
SET APPENDER_NAME='Test3';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%H');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.FATAL(LOGGER_ID, 'Message test');
SET EXPECTED_MSG=SYSPROC.MON_GET_APPLICATION_HANDLE();
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS;
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test4: Check the current user.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test4: Check the current user');
DELETE FROM LOGDATA.CONF_LOGGERS;
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_LOGGERS (LOGGER_ID, NAME, PARENT_ID, LEVEL_ID)
  VALUES (0, 'ROOT', NULL, 5);
SET LOGGER_NAME = 'Test4';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
INSERT INTO LOGDATA.CONF_LOGGERS (LOGGER_ID, NAME, PARENT_ID, LEVEL_ID)
  VALUES (LOGGER_ID, LOGGER_NAME, 0, 5);
SET APPENDER_NAME='Test4';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%S');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.FATAL(LOGGER_ID, 'Message test');
SET EXPECTED_MSG=TRIM(SESSION_USER);
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS;
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test5: Check the client.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test5: Check the client');
DELETE FROM LOGDATA.CONF_LOGGERS;
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_LOGGERS (LOGGER_ID, NAME, PARENT_ID, LEVEL_ID)
  VALUES (0, 'ROOT', NULL, 5);
SET LOGGER_NAME = 'Test5';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
INSERT INTO LOGDATA.CONF_LOGGERS (LOGGER_ID, NAME, PARENT_ID, LEVEL_ID)
  VALUES (LOGGER_ID, LOGGER_NAME, 0, 5);
SET APPENDER_NAME='Test5';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%C');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.FATAL(LOGGER_ID, 'Message test');
SET EXPECTED_MSG=CLIENT WRKSTNNAME;
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS;
DELETE FROM LOGDATA.CONF_LOGGERS_EFFECTIVE WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Tester empty layout
-- Tester string layout
-- Tests other letter with %

-- Root logger esta fallando: call logger.fatal(0,'fdsfadf')
END@

























