--#SET TERMINATOR @

/*
Copyright (c) 2012 - 2014, Andres Gomez Casanova (AngocA)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/**
 * Tests the layout of the conf_appenders table.
 */

SET CURRENT SCHEMA LOGGER_1B @

BEGIN
-- Reserved names for errors.
DECLARE SQLCODE INTEGER DEFAULT 0;
DECLARE SQLSTATE CHAR(5) DEFAULT '00000';

DECLARE APPENDER_NAME ANCHOR LOGDATA.CONF_LOGGERS.NAME;
DECLARE APPENDER_ID ANCHOR LOGDATA.CONF_APPENDERS.REF_ID;
DECLARE EXPECTED_MSG ANCHOR LOGDATA.LOGS.MESSAGE;
DECLARE ACTUAL_MSG ANCHOR LOGDATA.LOGS.MESSAGE;
DECLARE LOGGER_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID;
DECLARE PARENT_LOGGER_ID ANCHOR LOGDATA.CONF_LOGGERS.LOGGER_ID;
DECLARE LOGGER_NAME ANCHOR LOGDATA.CONF_LOGGERS.NAME;
DECLARE LVL_ID ANCHOR LOGDATA.LEVELS.LEVEL_ID;

-- Controlled SQL State.
DECLARE CONTINUE HANDLER FOR SQLWARNING
  INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (4, 'Warning SQLCode ' || SQLCODE || '-SQLState ' || SQLSTATE);
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
  INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (4, 'Exception SQLCode ' || SQLCODE || '-SQLState ' || SQLSTATE);
DECLARE CONTINUE HANDLER FOR NOT FOUND
  INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (5, 'Not found SQLCode ' || SQLCODE || '-SQLState ' || SQLSTATE);

-- Prepares the environment.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (4, 'TestsLayout: Preparing environment');
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS;
COMMIT;

-- Test1: Check the id.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test1: Check the id');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test1';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test1';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%I');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, 'Message test');
SET EXPECTED_MSG=SYSPROC.MON_GET_APPLICATION_ID();
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test2: Check the application name.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test2: Check the application name');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test2';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test2';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%N');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, 'Message test');
SELECT APPLICATION_NAME INTO EXPECTED_MSG
  FROM TABLE(MON_GET_CONNECTION(SYSPROC.MON_GET_APPLICATION_HANDLE(),-1));
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test3: Check the handle.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test3: Check the handle');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test3';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test3';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%H');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, 'Message test');
SET EXPECTED_MSG=SYSPROC.MON_GET_APPLICATION_HANDLE();
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test4: Check the current user.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test4: Check the current user');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test4';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test4';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%S');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, 'Message test');
SET EXPECTED_MSG=TRIM(SESSION_USER);
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test5: Check the client.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test5: Check the client');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test5';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test5';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%C');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, 'Message test');
SET EXPECTED_MSG=CLIENT WRKSTNNAME;
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test6: Check the message.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test6: Check the message');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test6';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test6';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%m');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
SET EXPECTED_MSG='No message';
CALL LOGGER.DEBUG(LOGGER_ID, EXPECTED_MSG);
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test7: Check the message null.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test7: Check the message null');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test7';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test7';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%m');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, NULL);
SET EXPECTED_MSG='No message';
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test8: Check the logger - ROOT.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test8: Check the logger - ROOT');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET APPENDER_NAME='Test8';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%c');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (0, APPENDER_ID);
CALL LOGGER.DEBUG(0, 'Message test');
SET EXPECTED_MSG='ROOT';
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test9: Check the logger - A.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test9: Check the logger - A');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test9';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test9';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%c');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, 'Message test');
SET EXPECTED_MSG=LOGGER_NAME;
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test10: Check the logger - A.B.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test10: Check the logger - A.B');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test10';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, PARENT_LOGGER_ID);
SET LOGGER_NAME = 'Test10.B';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = LOGGER_ID;
SET APPENDER_NAME='Test10';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%c');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, 'Message test');
SET EXPECTED_MSG='Test10.B';
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test11: Check the logger - A.B.C.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test11: Check the logger - A.B.C');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test11';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, PARENT_LOGGER_ID);
SET LOGGER_NAME = 'Test11.B';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET PARENT_LOGGER_ID=LOGGER_ID;
SET LOGGER_NAME = 'Test11.B.C';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test11';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%c');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, 'Message test');
SET EXPECTED_MSG=LOGGER_NAME;
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test12: Check the level.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test12: Check the level');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test12';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET LVL_ID=5;
SET APPENDER_NAME='Test12';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%p');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.LOG(LOGGER_ID, LVL_ID, 'Message test');
SELECT UCASE(L.NAME) INTO EXPECTED_MSG
  FROM LOGDATA.LEVELS L
  WHERE L.LEVEL_ID = LVL_ID
  WITH UR;
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, LVL_ID || 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test13: Check the nesting level.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test13: Check the nesting level');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test13';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET LVL_ID=5;
SET APPENDER_NAME='Test13';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%L');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.LOG(LOGGER_ID, LVL_ID, 'Message test');
SET EXPECTED_MSG = '2';
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, LVL_ID || 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test14: Check the pattern layout static.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test14: Check the pattern layout static');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test14';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test14';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, 'static layout');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, NULL);
SET EXPECTED_MSG='static layout';
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test15: Check the pattern layout empty.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test15: Check the pattern layout empty');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test15';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test15';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, NULL);
SET EXPECTED_MSG='';
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test16: Check the pattern layout %a.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test16: Check the pattern layout %a');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test16';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test16';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%a');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, NULL);
SET EXPECTED_MSG='%a';
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Test17: Check the pattern layout with reserved words.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'Test17: Check the pattern layout reserved words');
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
UPDATE LOGDATA.CONF_LOGGERS
  SET LEVEL_ID = 5
  WHERE LOGGER_ID = 0;
SET LOGGER_NAME = 'Test17';
CALL LOGGER.GET_LOGGER(LOGGER_NAME, LOGGER_ID);
SET APPENDER_NAME='Test17';
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES (APPENDER_NAME, 1, NULL, '%m');
SELECT MAX(REF_ID) INTO APPENDER_ID
  FROM LOGDATA.CONF_APPENDERS;
INSERT INTO LOGDATA.REFERENCES (LOGGER_ID, APPENDER_REF_ID)
  VALUES (LOGGER_ID, APPENDER_ID);
CALL LOGGER.DEBUG(LOGGER_ID, '%c %m %p %C %H %I %L %N %S');
SET EXPECTED_MSG='%c %m %p %C %H %I %L %N %S';
SELECT MESSAGE INTO ACTUAL_MSG
  FROM LOGS
  WHERE DATE = (SELECT MAX(DATE)
    FROM LOGS);
IF (EXPECTED_MSG <> ACTUAL_MSG) THEN
 INSERT INTO LOGDATA.LOGS (DATE, LEVEL_ID, MESSAGE) VALUES 
   (GENERATE_UNIQUE(), 2, 'Different msg, expected "' || COALESCE(EXPECTED_MSG, '-') || '" actual "' || COALESCE(ACTUAL_MSG, '-') || '"');
END IF;
DELETE FROM LOGDATA.REFERENCES;
DELETE FROM LOGDATA.CONF_APPENDERS
  WHERE REF_ID = APPENDER_ID;
DELETE FROM LOGDATA.CONF_LOGGERS WHERE LOGGER_ID <> 0;
INSERT INTO LOGDATA.CONF_APPENDERS (NAME, APPENDER_ID, CONFIGURATION, PATTERN)
  VALUES ('DB2 Tables', 1, NULL, '[%p] %c - %m');
COMMIT;

-- Cleans the environment.
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'TestsLayout: Cleaning environment');
INSERT INTO LOGDATA.LOGS (LEVEL_ID, MESSAGE) VALUES (3, 'TestsLayout: Finished succesfully');
COMMIT;

END@
