--#SET TERMINATOR @

-- Drops all matrix objects.
--
-- Author: Andres Gomez
-- Version: 20220529

DROP PROCEDURE PRINT_INTEGER_MATRIX@
DROP PROCEDURE INIT_INTEGER_MATRIX@
DROP PROCEDURE SET_INTEGER_VALUE@
DROP FUNCTION GET_INTEGER_VALUE@
DROP TYPE INTEGER_MATRIX@
DROP TYPE INTEGER_ARRAY@